# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Papaoutai' do

  use_frameworks!
    pod 'BlueCapKit', '~> 0.7'
    pod 'Alamofire', '~> 5.2'
pod 'SwiftyJSON', '~> 4.0'

  # Pods for Papaoutai

  target 'PapaoutaiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PapaoutaiUITests' do
    # Pods for testing
  end

end
