# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Papaoutai_charts' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'Charts'
pod 'TinyConstraints'
pod 'FSCalendar'

  # Pods for Papaoutai_charts

end
